services:
  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    environment:
      - ENV

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./config/redis.conf:/usr/local/etc/redis/redis.conf"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - "./config/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
