services:
  server:
    build: .
    ports:
      - 8080
    deploy:
      replicas: 3
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    environment:
      - ENV
      - BASE_URL=http://localhost
    networks:
      - miniurl_network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./config/redis.conf:/usr/local/etc/redis/redis.conf"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - miniurl_network

  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - "./config/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
    networks:
      - miniurl_network

  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - server
    networks:
      - miniurl_network

networks:
  miniurl_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/20
