CREATE DATABASE miniurl OWNER admin;

\c miniurl

CREATE TABLE slugs (
	id SERIAL PRIMARY KEY,
	slug CHAR(10) NOT NULL,
	url TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	expires_at TIMESTAMP
);